name: Xunet.MiniApi
 
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ master ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.100
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
       PROJECT_FILE_PATH: src/Xunet.MiniApi.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
